### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by Tsukiaa** [Dewset/Dewset#1]
请问有同花顺算法大赛金融因果关系数据集吗？

**Comment by Dewset** [comment]
> 请问有同花顺算法大赛金融因果关系数据集吗？

http://contest.aicubes.cn/#/detail?topicId=84，这个吗？

**Comment by Dewset** [comment]
> 请问有同花顺算法大赛金融因果关系数据集吗？

http://contest.aicubes.cn/#/detail?topicId=84
这个吗

**Comment by Dewset** [comment]
> 请问有同花顺算法大赛金融因果关系数据集吗？

http://contest.aicubes.cn/#/detail?topicId=84
这个吗？

**Comment by Tsukiaa** [comment]
是的，是这个大赛











在 2023-02-05 19:44:10，"Zhiyu Cao" ***@***.***> 写道：

请问有同花顺算法大赛金融因果关系数据集吗？

http://contest.aicubes.cn/#/detail?topicId=84
这个吗

**Comment by Tsukiaa** [comment]
可以分享一下吗？

**Comment by Dewset** [comment]
> 可以分享一下吗？

官网上的好像不能下载了，可以看一下其他相关的数据集：https://tianchi.aliyun.com/dataset/110901。

**Comment by Dewset** [comment]
> 可以分享一下吗？

官网上的好像不能下载了，可以看一下其他相关的数据集：https://tianchi.aliyun.com/dataset/110901

**Comment by Tsukiaa** [comment]
好的，谢谢了！











在 2023-02-05 20:03:13，"Zhiyu Cao" ***@***.***> 写道：

可以分享一下吗？

官网上的好像不能下载了，可以看一下其他相关的数据集：https://tianchi.aliyun.com/dataset/110901
